/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.unsane.spirit;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int SpiritDarkBlue=0x7f070001;
        /** COLOR________________________________________________________________________________________________________
         */
        public static final int SpiritLightBlue=0x7f070000;
        public static final int SpiritWhite=0x7f070002;
    }
    public static final class drawable {
        public static final int background=0x7f020000;
        public static final int logo_spirit_transp=0x7f020001;
        public static final int logo_spirit_v03_hdpi=0x7f020002;
        public static final int logo_spirit_v03_ldpi=0x7f020003;
        public static final int menu_news_bs=0x7f020004;
        public static final int menu_timetable_bs=0x7f020005;
        public static final int menu_writenews_bs=0x7f020006;
        public static final int newsbackgroundheader=0x7f020007;
        public static final int newsbackgroundsmall2=0x7f020008;
        public static final int optmenubg=0x7f020009;
        public static final int optmenuhelp_l=0x7f02000a;
        public static final int optmenuuser_l=0x7f02000b;
    }
    public static final class id {
        public static final int createButton=0x7f090003;
        public static final int datePexpiredegreeText=0x7f090009;
        public static final int degreeText=0x7f090008;
        public static final int editMessage=0x7f090007;
        public static final int editSubject=0x7f090005;
        public static final int grid=0x7f090002;
        public static final int help=0x7f090010;
        public static final int infowebview=0x7f090000;
        public static final int lastNewsDate=0x7f09000c;
        public static final int menulogo=0x7f090001;
        public static final int newsMain=0x7f09000b;
        public static final int newsScroll=0x7f09000a;
        public static final int newsSingleMain=0x7f09000d;
        public static final int reload=0x7f09000e;
        public static final int tvMessage=0x7f090006;
        public static final int tvSubject=0x7f090004;
        public static final int userdata=0x7f09000f;
    }
    public static final class layout {
        public static final int info=0x7f030000;
        public static final int mainactivity=0x7f030001;
        public static final int newscreate=0x7f030002;
        public static final int newsmulti=0x7f030003;
        public static final int newssingle=0x7f030004;
    }
    public static final class menu {
        public static final int newsmulti=0x7f080000;
        public static final int options=0x7f080001;
    }
    public static final class raw {
        public static final int info=0x7f050000;
        public static final int mykeystore=0x7f050001;
    }
    public static final class string {
        /** STRINGS______________________________________________________________________________________________________
General
         */
        public static final int app_name=0x7f060002;
        public static final int err_erroroccured=0x7f060018;
        /** ERRORS_______________________________________________________________________________________________________
         */
        public static final int err_noInternet=0x7f060017;
        public static final int err_notImplementedYet=0x7f060019;
        public static final int ipadress=0x7f060000;
        public static final int menu_createNews=0x7f06000c;
        /** MainMenu
         */
        public static final int menu_news=0x7f06000b;
        public static final int menu_timetable=0x7f06000d;
        public static final int port=0x7f060001;
        public static final int string_all=0x7f060011;
        public static final int string_commentsCount=0x7f060006;
        public static final int string_commess_must=0x7f06000a;
        public static final int string_enterUnAndPass=0x7f060016;
        public static final int string_group=0x7f060012;
        /** News
         */
        public static final int string_lastNewsFetch=0x7f060004;
        public static final int string_loggedInAs=0x7f060015;
        public static final int string_newComment=0x7f060007;
        public static final int string_notLoggedIn=0x7f060014;
        /** Settings
         */
        public static final int string_notSetYet=0x7f060013;
        public static final int string_oclock=0x7f060009;
        public static final int string_regardingDegrees=0x7f060005;
        public static final int string_sendComment=0x7f060008;
        /** NewsCreate
         */
        public static final int string_send_as=0x7f06000e;
        public static final int string_subjMess_must=0x7f06000f;
        public static final int string_valid_till=0x7f060010;
        public static final int trialPassphrase=0x7f060003;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
